### ISSUE TITLE
Issue with site load

### ISSUE THREAD

**Issue by jshirleygeo** [ngageoint/mage-server#140]
Has anyone seen this?
![image](https://user-images.githubusercontent.com/107219961/189460973-d6542337-0031-4b29-b0f9-1bb15a450aad.png)

I used nvm 14, npm latest, ubuntu 20. Using forever to load the site with the site listening on 4242 but no luck loading its contents.

**Comment by newmanw** [comment]
To verify the server is running you can hit the /api route. My guess is you haven’t built the web app; https://github.com/ngageoint/mage-server#web-application

**Comment by jshirleygeo** [comment]
Gotcha, thank you. I'll take a look at that.
