### ISSUE TITLE
Cannot get passed "Enter your device ID to continue to MAGE" after login

### ISSUE THREAD

**Issue by jrip-geo** [ngageoint/mage-server#142]
I am using the mage-server via nginx ssl proxy. I was able to activate the user via mongodb but now it requests the user for a Device ID. How do you provide the user a Device ID?
![image](https://user-images.githubusercontent.com/107219961/196304992-28661520-480c-4434-8fd7-6e19941809cf.png)
If this is not normal, how do you get pass this or turn off this requirement?

**Comment by jrip-geo** [comment]
UPDATE:
This issue is observed when a user tries to first login through the mage web page on a Desktop. If a user logins with the mobile app the request/generation for a DeviceID is generated in the db.devices. There you can update the registered key to true and then retry login into the server web interface with the objectid of the device. 

New problem: 
When the user is logged into the mobile app at this point the user gets a page that says "No Events, you must be a member of at least one event to use mage". I am stuck at this point as I dont know how to add an event to a user or manage events. Is there an admin login?

**Comment by jrip-geo** [comment]
UPDATE:
instructions should include information on how to become admin in order to get access to pages such as event creation. I was able to add myself to the admin role through mongo and now I'm able to see everything. Issue resolved.

**Comment by newmanw** [comment]
You should not have needed to create anything through mongo. The issue was you created the initial user without creating the initial web id. If you spin up the web server and the database is empty you will be walked through creating the first user, which will be and admin user, along with the initial web id.
