### ISSUE TITLE
[Documentation] How to configure db connection

### ISSUE THREAD

**Issue by benhosmer** [ngageoint/mage-server#33]
I see a cloudfoundry environment configuration and a local configuration, how would I configure this to use a different cloud provider? 

For example, my database uri is provided as an environment variable, how can I tell mage what this is?

**Comment by newmanw** [comment]
@benhosmer you need create a new environment module.  Both the local and cloudfoundry envs are modules.  The easiest way would be to copy the contents of the cloudfoundry directory to a new directory in the environment dir.

From there just change the the mongo variable to pull what it needs from the environment: https://github.com/ngageoint/mage-server/blob/master/environment/cloudfoundry/env.js#L11-L20

You would need to change this file to key off of some unique env for your cloud provider:
https://github.com/ngageoint/mage-server/blob/master/environment/env.js

IE
```
var env;
if (process.env.CLOUDFOUNDRY) {
 env = require('cloudfoundry-environment');
} else if (process.env.OPENSHIFT) {
 // not sure if open shift provides an OPENSHIFT env variable.
 // if not change process.env.OPENSHIFT to something unique that is does provide to indicate
 // your env is open shift
 env = require('local-environment');
} else {
 env =  require('local-environment');
}

module.exports =  env;
```

If you have already done an npm install you will either need to bump the version number on the environment module or wipe out the environment-* modules in the node_modules directory.  Then npm install again.  This will pick up and install the changes that you made to the environment module.

**Comment by benhosmer** [comment]
@newmanw thanks for the quick response on this. I haven't had a chance to try it out, but I'll report back if I have any more issues.
