### ISSUE TITLE
NODEJS

### ISSUE THREAD

**Issue by dbesch** [ngageoint/mage-server#34]
I'm having issues downloading Node.js on Ubuntu 16, I've tried curl, wget and even apt-get install with no luck.  Are you experiencing any issues with a fresh install?

**Comment by newmanw** [comment]
I would recommend using NVM (Node Version Manager), as its a lot easier to get exact install of node you are looking for.

Have you tried these steps:
https://github.com/ngageoint/mage-server/blob/develop/README.md#nodejs-setup

**Comment by dbesch** [comment]
Yes. Ive tried that.  Juat says verison 12 not found. Ive even tried 33 and nothing. Tried it as root and no luck. 


Sent via the Samsung Galaxy S8+, an AT&T 4G LTE smartphone
-------- Original message --------From: Billy Newman <notifications@github.com> Date: 7/3/17  9:48 AM  (GMT-05:00) To: ngageoint/mage-server <mage-server@noreply.github.com> Cc: dbesch <donaldbesch@ymail.com>, Author <author@noreply.github.com> Subject: Re: [ngageoint/mage-server] NODEJS (#34) 
I would recommend using NVM (Node Version Manager), as its a lot easier to get exact install of node you are looking for.
Have you tried these steps:

https://github.com/ngageoint/mage-server/blob/develop/README.md#nodejs-setup

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ngageoint/mage-server","title":"ngageoint/mage-server","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ngageoint/mage-server"}},"updates":{"snippets":[{"icon":"PERSON","message":"@newmanw in #34: I would recommend using NVM (Node Version Manager), as its a lot easier to get exact install of node you are looking for.\r\n\r\nHave you tried these steps:\r\nhttps://github.com/ngageoint/mage-server/blob/develop/README.md#nodejs-setup"}],"action":{"name":"View Issue","url":"https://github.com/ngageoint/mage-server/issues/34#issuecomment-312650402"}}}

**Comment by newmanw** [comment]
@dbesch can you show me the commands you are running?  As well as the version of Ubuntu?

**Comment by dbesch** [comment]
Ubuntu 16 and i copy and paste line for line. 


Sent via the Samsung Galaxy S8+, an AT&T 4G LTE smartphone
-------- Original message --------From: Billy Newman <notifications@github.com> Date: 7/3/17  11:07 AM  (GMT-05:00) To: ngageoint/mage-server <mage-server@noreply.github.com> Cc: dbesch <donaldbesch@ymail.com>, Mention <mention@noreply.github.com> Subject: Re: [ngageoint/mage-server] NODEJS (#34) 
@dbesch can you show me the commands you are running?  As well as the version of Ubuntu?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ngageoint/mage-server","title":"ngageoint/mage-server","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ngageoint/mage-server"}},"updates":{"snippets":[{"icon":"PERSON","message":"@newmanw in #34: @dbesch can you show me the commands you are running?  As well as the version of Ubuntu?"}],"action":{"name":"View Issue","url":"https://github.com/ngageoint/mage-server/issues/34#issuecomment-312670642"}}}

**Comment by newmanw** [comment]
@dbesch I am sorry you are having problems.  Please provide your commands as well as the console output.  Without that information its hard to tell what is going on.

As an example here is my console with a fresh nvm and node install on Ubuntu 16:

```
ubuntu:~$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11699  100 11699    0     0  31514      0 --:--:-- --:--:-- --:--:-- 31448
=> Downloading nvm from git to '/home/ubuntu/.nvm'
=> Cloning into '/home/ubuntu/.nvm'...
remote: Counting objects: 6474, done.
remote: Total 6474 (delta 0), reused 0 (delta 0), pack-reused 6474
Receiving objects: 100% (6474/6474), 1.91 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4015/4015), done.
Checking connectivity... done.
* (HEAD detached at v0.33.2)
  master
=> Compressing and cleaning up git repository
Counting objects: 6474, done.
Compressing objects: 100% (6430/6430), done.
Writing objects: 100% (6474/6474), done.
Total 6474 (delta 4288), reused 1989 (delta 0)

=> Appending nvm source string to /home/ubuntu/.bashrc
=> Appending bash_completion source string to /home/ubuntu/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
ubunt8:~$


ubunt8:~$ source ~/.bashrc

ubuntu:~$ nvm install v0.12.2
Downloading and installing node v0.12.2...
Downloading https://nodejs.org/dist/v0.12.2/node-v0.12.2-linux-x64.tar.gz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Creating default alias: default -> v0.12.2
ubuntu:~$

ubuntu:~$ node --version
v0.12.2
```

**Comment by dbesch** [comment]
I will copy and paste your commands and see what happens.  If that doesn't work I will send you copy of my shell inputs and outputs. 

    On Monday, July 3, 2017 8:54 PM, Billy Newman <notifications@github.com> wrote:
 

 @dbesch I am sorry you are having problems. Please provide your commands as well as the console output. Without that information its hard to tell what is going on.As an example here is my console with a fresh nvm and node install on Ubuntu 16:ubuntu:~$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11699  100 11699    0     0  31514      0 --:--:-- --:--:-- --:--:-- 31448
=> Downloading nvm from git to '/home/ubuntu/.nvm'
=> Cloning into '/home/ubuntu/.nvm'...
remote: Counting objects: 6474, done.
remote: Total 6474 (delta 0), reused 0 (delta 0), pack-reused 6474
Receiving objects: 100% (6474/6474), 1.91 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4015/4015), done.
Checking connectivity... done.
* (HEAD detached at v0.33.2)
  master
=> Compressing and cleaning up git repository
Counting objects: 6474, done.
Compressing objects: 100% (6430/6430), done.
Writing objects: 100% (6474/6474), done.
Total 6474 (delta 4288), reused 1989 (delta 0)

=> Appending nvm source string to /home/ubuntu/.bashrc
=> Appending bash_completion source string to /home/ubuntu/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
ubunt8:~$


ubunt8:~$ source ~/.bashrc

ubuntu:~$ nvm install v0.12.2
Downloading and installing node v0.12.2...
Downloading https://nodejs.org/dist/v0.12.2/node-v0.12.2-linux-x64.tar.gz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Creating default alias: default -> v0.12.2
ubuntu:~$

ubuntu:~$ node --version
v0.12.2
