### ISSUE TITLE
npm run migrate issue?

### ISSUE THREAD

**Issue by toddk** [ngageoint/mage-server#38]
Having an issue with the initial setup and configuration of the MAGE server. I'm able to get all of the dependencies installed and if I skip the `npm run migrate` and go straight to `npm build run` and then `node app.js` I get the setup page to establish an initial account (although this part does fail).

I've attached the `npm-debug.log` file here.

[npm-debug.log](https://github.com/ngageoint/mage-server/files/1412457/npm-debug.log)

**Comment by toddk** [comment]
Also forgot to mention that I'm trying to run this locally on a MacBook Pro running High Sierra.

**Comment by newmanw** [comment]
@toddk sorry about that.  There is typo README that pointed to an old version of the server.

Substitute <version> with the latest release, which in this case is 4.5.2
https://github.com/ngageoint/mage-server#running-mage

There was a bug introduced in one of our dependencies in 4.4.3 that caused a bug with migrate.

**Comment by toddk** [comment]
Thanks, that solved it for me!
