### ISSUE TITLE
add Text Note not just attachments with location

### ISSUE THREAD

**Issue by geospatialmapmashup** [ngageoint/mage-server#41]
One feature I think is really needed is just a free form text field

**Comment by newmanw** [comment]
Absolutely, that feature is already supported.

What you will need to do is create a form or forms for your event.  Forms can contain any number custom fields, ie text, select, number, etc.

Go to your event and add a form by clicking the "New Form" button:
![screen shot 2018-04-12 at 10 36 14 am](https://user-images.githubusercontent.com/3382274/38691226-7ab5f89e-3e3d-11e8-902a-89e119e8ab28.png)

From there add your text area field by selecting a 'Text Area' and clicking the "Add Field" button.  Don't forget to save your form after adding the field.
![screen shot 2018-04-12 at 10 37 59 am](https://user-images.githubusercontent.com/3382274/38691378-ebb10386-3e3d-11e8-8060-6a49f3008ec8.png)


Form with added field:
![screen shot 2018-04-12 at 10 41 02 am](https://user-images.githubusercontent.com/3382274/38691407-0393b4d0-3e3e-11e8-92dc-f383ad73b006.png)
