### ISSUE TITLE
Use MAGE with custom SSO?

### ISSUE THREAD

**Issue by JoshMcCullough** [ngageoint/mage-server#51]
Me again. We are using MAGE with SSO. Basically we sync user account from our system to MAGE. Then, when a user is heading to MAGE, they go through single-sign-on which logs them in behind the scenes and then sets the resulting `mage-session` and `mage-session.sig` cookies. We then redirect to MAGE.

Once the user is redirected, they are still being prompted to login. I have verified that the two cookies exist. But I am not sure how to also set the `token` which results from our behind-the-scenes call to `auth/local/authorize`. Can it be set as a cookie as well, or can I include it in the URL we redirect to, or is there another way for the UI to pick up the token after we redirect?

PS: The response to `GET /api/settings/banner`, after the redirect, is `401` with the header `www-authenticate: Bearer realm="Users", error="invalid_token"` -- which is accurate since we haven't set the token.

**Comment by newmanw** [comment]
The cookie is only used between user authentication and device authorization.  Once the call is made to authorize the device a MAGE token is issued in the response. All MAGE api routes use an HTTP bearer strategy, pass the api token in the Authorization header and you should be good to go.

**Comment by newmanw** [comment]
If you have more questions it might be best to hit us up @ mage@nga.mil.

**Comment by JoshMcCullough** [comment]
Great I'll give it a try. Will use that email going forward.

**Comment by JoshMcCullough** [comment]
Sent an email as requested -- thanks.
