### ISSUE TITLE
cant seem to get passed the login section requesting for a device id

### ISSUE THREAD

**Issue by Jufi-101** [ngageoint/mage-server#54]
I setup the mage server, created a anew account on the web app. but after requesting for the device uid. it does not do anything on clicking the finish button.

**Comment by newmanw** [comment]
Sounds like you are connecting via http (not https).  You will need to set the following env variable to false.
https://github.com/ngageoint/mage-server/blob/master/environment/magerc.sh#L7-L8

Note that the magerc.sh is not automatically sourced.  Read more here:
https://github.com/ngageoint/mage-server#mage-environment-settings

**Comment by hmorilak** [comment]
I'm having the same issue. I tried setting the MAGE_SESSION_COOKIE_SECURE variable to false and now I'm unable to access the server from my browser. @Jufi-101 were you able to get this fixed?

**Comment by newmanw** [comment]
See: https://github.com/ngageoint/mage-server/issues/57#issuecomment-525035124
